//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocaLabs.Storage.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocaLabs.Storage.Core.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faled to get the connection string for the partition {0}..
        /// </summary>
        internal static string failed_get_connection_string_for_partition_0 {
            get {
                return ResourceManager.GetString("failed_get_connection_string_for_partition_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faled to get the connection string for the partition key {0}..
        /// </summary>
        internal static string failed_get_connection_string_for_partition_key_0 {
            get {
                return ResourceManager.GetString("failed_get_connection_string_for_partition_key_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The get unique query returned more than one entity..
        /// </summary>
        internal static string get_unique_returned_more_than_one_entity {
            get {
                return ResourceManager.GetString("get_unique_returned_more_than_one_entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error, see the inner exception..
        /// </summary>
        internal static string internal_error_see_inner_exception {
            get {
                return ResourceManager.GetString("internal_error_see_inner_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one property as markes by KeyAttribute in entity {0}, the result maybe unpredictable as reflection doesn&apos;t guarantee the order of attributes..
        /// </summary>
        internal static string more_than_one_property_marked_as_primary_key_in_0 {
            get {
                return ResourceManager.GetString("more_than_one_property_marked_as_primary_key_in_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no any key defined for entity {0}..
        /// </summary>
        internal static string no_key_defined_for_entity_0 {
            get {
                return ResourceManager.GetString("no_key_defined_for_entity_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no matching key property {0} for entity {1}..
        /// </summary>
        internal static string no_matching_key_property_0_for_entity_1 {
            get {
                return ResourceManager.GetString("no_matching_key_property_0_for_entity_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of key properties doesn&apos;t match number of passed values for entity {0}..
        /// </summary>
        internal static string number_of_key_properties_doesn_match_values_for_entity_0 {
            get {
                return ResourceManager.GetString("number_of_key_properties_doesn_match_values_for_entity_0", resourceCulture);
            }
        }
    }
}
